apiVersion: v1
kind: Service
metadata:
  name: {{ include "cobalt-strike.fullname" . }}
  labels:
    {{- include "cobalt-strike.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "cobalt-strike.selectorLabels" . | nindent 4 }}