apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack
  namespace: argocd
spec:
  project: default
  source:
    targetRevision: kube-prometheus-stack-56.0.1
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack
    helm:
      values: |-
        grafana:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - grafana.red.ops
        prometheus:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - prometheus.red.ops
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  resources:
                   requests:
                     storage: 1Gi
            retentionSize: 800MiB
        alertmanager:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - alertmanager.red.ops
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 1Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true