apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    targetRevision: loki-stack-2.10.1
    repoURL: https://github.com/grafana/helm-charts.git
    path: charts/loki-stack
    helm:
      values: |-
        test_pod:
          enabled: false
        loki:
          enabled: true
          isDefault: true
          url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          datasource:
            jsonData: "{}"
            uid: ""
        promtail:
          enabled: true
          config:
            logLevel: info
            serverPort: 3101
            clients:
              - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
        grafana:
          enabled: false
        
        prometheus:
          enabled: false

        filebeat:
          enabled: false
  
        logstash:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true