apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pwndrop
  namespace: argocd
spec:
  project: default
  source:
    targetRevision: develop
    repoURL: https://github.com/3ayazaya/DevRedOps.git
    path: charts/pwndrop
    helm:
      values: |-
        image:
          repository: linuxserver/pwndrop
          tag: "latest"
        service:
         type: LoadBalancer
         port: 80
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: pwndrop.red.ops
              paths:
                - path: /
                  pathType: ImplementationSpecific

  destination:
    server: "https://kubernetes.default.svc"
    namespace: redops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true